version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    networks:
      - default
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./docker/php
    container_name: php
    restart: always
    env_file: ./.env
    volumes:
      - ./:/var/www
    networks:
      - default
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yusehng123456
    networks:
      - default
networks:
  default:
    external:
      name: project_default
